const CATEGORIES = {
  AI: 'AI',
  CONVERT: 'CONVERT',
  DOWNLOADER: 'DOWNLOADER',
  FUN: 'FUN',
  GROUP: 'GROUP',
  MAIN: 'MAIN',
  OWNER: 'OWNER',
  STORE: 'STORE',
  TOOLS: 'TOOLS',
};

const make = ({ name, aliases = [], category, description, usage, role = 'member', needsArgs = false, premiumOnly = false, vipOnly = false }) => ({
  name,
  aliases,
  category,
  description,
  usage,
  role,
  needsArgs,
  premiumOnly,
  vipOnly,
});

const commands = [
  // AI
  make({ name: 'elainaai', category: CATEGORIES.AI, description: 'Chat AI Elaina (stub).', usage: 'a elainaai halo', needsArgs: true }),
  make({ name: 'sonu', category: CATEGORIES.AI, description: 'Chat AI Sonu (stub).', usage: 'a sonu halo', needsArgs: true }),

  // CONVERT
  make({ name: 'convert', category: CATEGORIES.CONVERT, description: 'Konversi media umum (stub).', usage: 'a convert <opsi>' }),
  make({ name: 'convertfile', category: CATEGORIES.CONVERT, description: 'Konversi file (stub).', usage: 'a convertfile <opsi>' }),
  make({ name: 'pdf', category: CATEGORIES.CONVERT, description: 'Buat PDF (stub).', usage: 'a pdf <konten>' }),
  make({ name: 'topdf', category: CATEGORIES.CONVERT, description: 'Konversi ke PDF (stub).', usage: 'a topdf <file>' }),
  make({ name: 'smeme', category: CATEGORIES.CONVERT, description: 'Sticker meme (stub).', usage: 'a smeme teks atas|teks bawah', needsArgs: true }),
  make({ name: 'sticker', aliases: ['s'], category: CATEGORIES.CONVERT, description: 'Buat stiker (stub).', usage: 'a sticker' }),
  make({ name: 'toimage', category: CATEGORIES.CONVERT, description: 'Sticker ke image (stub).', usage: 'a toimage' }),
  make({ name: 'tovoice', category: CATEGORIES.CONVERT, description: 'Audio ke voice note (stub).', usage: 'a tovoice' }),

  // DOWNLOADER
  make({ name: 'fbdl', category: CATEGORIES.DOWNLOADER, description: 'Download Facebook (stub).', usage: 'a fbdl <url>', needsArgs: true }),
  make({ name: 'gdrivedl', category: CATEGORIES.DOWNLOADER, description: 'Download Google Drive (stub).', usage: 'a gdrivedl <url>', needsArgs: true }),
  make({ name: 'igdl', category: CATEGORIES.DOWNLOADER, description: 'Download Instagram (stub).', usage: 'a igdl <url>', needsArgs: true }),
  make({ name: 'mediafiredl', category: CATEGORIES.DOWNLOADER, description: 'Download Mediafire (stub).', usage: 'a mediafiredl <url>', needsArgs: true }),
  make({ name: 'play', category: CATEGORIES.DOWNLOADER, description: 'Cari & download musik (stub).', usage: 'a play <judul>', needsArgs: true }),
  make({ name: 'sfile', category: CATEGORIES.DOWNLOADER, description: 'Download Sfile (stub).', usage: 'a sfile <url>', needsArgs: true }),
  make({ name: 'spotifydl', aliases: ['spdl'], category: CATEGORIES.DOWNLOADER, description: 'Download Spotify (stub).', usage: 'a spotifydl <url>', needsArgs: true }),
  make({ name: 'teraboxdl', category: CATEGORIES.DOWNLOADER, description: 'Download Terabox (stub).', usage: 'a teraboxdl <url>', needsArgs: true }),
  make({ name: 'tredl', category: CATEGORIES.DOWNLOADER, description: 'Download Threads (stub).', usage: 'a tredl <url>', needsArgs: true }),
  make({ name: 'tt', aliases: ['ttmusic'], category: CATEGORIES.DOWNLOADER, description: 'Download TikTok (stub).', usage: 'a tt <url>', needsArgs: true }),
  make({ name: 'ytmp3', category: CATEGORIES.DOWNLOADER, description: 'Download YouTube MP3 (stub).', usage: 'a ytmp3 <url>', needsArgs: true }),
  make({ name: 'ytmp4', category: CATEGORIES.DOWNLOADER, description: 'Download YouTube MP4 (stub).', usage: 'a ytmp4 <url>', needsArgs: true }),

  // FUN
  make({ name: 'cekcantik', category: CATEGORIES.FUN, description: 'Cek kecantikan (stub).', usage: 'a cekcantik @tag' }),

  // GROUP
  make({ name: 'absen', category: CATEGORIES.GROUP, description: 'Mulai absen grup.', usage: 'a absen', role: 'admin' }),
  make({ name: 'berhentiabsen', category: CATEGORIES.GROUP, description: 'Stop absen grup.', usage: 'a berhentiabsen', role: 'admin' }),
  make({ name: 'listabsen', category: CATEGORIES.GROUP, description: 'Lihat list absen.', usage: 'a listabsen' }),
  make({ name: 'riwayatabsen', category: CATEGORIES.GROUP, description: 'Riwayat absen.', usage: 'a riwayatabsen' }),
  make({ name: 'rekapabsen', category: CATEGORIES.GROUP, description: 'Rekap absen.', usage: 'a rekapabsen' }),
  make({ name: 'totalabsen', category: CATEGORIES.GROUP, description: 'Total absen.', usage: 'a totalabsen' }),
  make({ name: 'resetabsen', category: CATEGORIES.GROUP, description: 'Reset absen.', usage: 'a resetabsen', role: 'admin' }),
  make({ name: 'acc', category: CATEGORIES.GROUP, description: 'Acc member (stub).', usage: 'a acc @tag', role: 'admin' }),
  make({ name: 'add', category: CATEGORIES.GROUP, description: 'Tambah member.', usage: 'a add 628xx', role: 'admin', needsArgs: true }),
  make({ name: 'afk', category: CATEGORIES.GROUP, description: 'Set AFK.', usage: 'a afk <alasan>' }),
  make({ name: 'anticall', category: CATEGORIES.GROUP, description: 'Anti call.', usage: 'a anticall on/off', role: 'admin' }),
  make({ name: 'antidelete', category: CATEGORIES.GROUP, description: 'Anti delete.', usage: 'a antidelete on/off', role: 'admin' }),
  make({ name: 'antilink', category: CATEGORIES.GROUP, description: 'Anti link.', usage: 'a antilink on/off', role: 'admin' }),
  make({ name: 'antispam', category: CATEGORIES.GROUP, description: 'Anti spam.', usage: 'a antispam on/off', role: 'admin' }),
  make({ name: 'antitagsw', category: CATEGORIES.GROUP, description: 'Anti tag SW.', usage: 'a antitagsw on/off', role: 'admin' }),
  make({ name: 'antitoxic', category: CATEGORIES.GROUP, description: 'Anti toxic.', usage: 'a antitoxic on/off', role: 'admin' }),
  make({ name: 'auto', category: CATEGORIES.GROUP, description: 'Auto mode grup.', usage: 'a auto on/off', role: 'admin' }),
  make({ name: 'autotagadmin', category: CATEGORIES.GROUP, description: 'Auto tag admin.', usage: 'a autotagadmin on/off', role: 'admin' }),
  make({ name: 'blacklist', category: CATEGORIES.GROUP, description: 'Kelola blacklist.', usage: 'a blacklist <opsi>', role: 'admin' }),
  make({ name: 'bot', category: CATEGORIES.GROUP, description: 'Aktif/nonaktif bot di grup.', usage: 'a bot <on/off>', role: 'admin', needsArgs: true }),
  make({ name: 'ceksewa', category: CATEGORIES.GROUP, description: 'Cek sewa grup.', usage: 'a ceksewa' }),
  make({ name: 'delete', category: CATEGORIES.GROUP, description: 'Hapus pesan.', usage: 'a delete', role: 'admin' }),
  make({ name: 'demote', category: CATEGORIES.GROUP, description: 'Turunkan admin.', usage: 'a demote 628xx', role: 'admin', needsArgs: true }),
  make({ name: 'deskripsigrup', category: CATEGORIES.GROUP, description: 'Ambil deskripsi grup dari link.', usage: 'a deskripsigrup [link]', needsArgs: true }),
  make({ name: 'group', category: CATEGORIES.GROUP, description: 'Buka/tutup grup.', usage: 'a group open/close', role: 'admin' }),
  make({ name: 'hidetag', category: CATEGORIES.GROUP, description: 'Tag semua member.', usage: 'a hidetag <teks>', role: 'admin' }),
  make({ name: 'kick', category: CATEGORIES.GROUP, description: 'Kick member.', usage: 'a kick 628xx', role: 'admin', needsArgs: true }),
  make({ name: 'left', category: CATEGORIES.GROUP, description: 'Toggle pesan left.', usage: 'a left <on/off>', role: 'admin', needsArgs: true }),
  make({ name: 'setleft', category: CATEGORIES.GROUP, description: 'Set template left.', usage: 'a setleft <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'changeleft', category: CATEGORIES.GROUP, description: 'Ubah template left.', usage: 'a changeleft <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'delsetleft', category: CATEGORIES.GROUP, description: 'Hapus template left.', usage: 'a delsetleft', role: 'admin' }),
  make({ name: 'linkgroup', category: CATEGORIES.GROUP, description: 'Ambil link grup.', usage: 'a linkgroup', role: 'admin' }),
  make({ name: 'listonline', category: CATEGORIES.GROUP, description: 'List member online.', usage: 'a listonline' }),
  make({ name: 'moderation', category: CATEGORIES.GROUP, description: 'Panel moderasi.', usage: 'a moderation', role: 'admin' }),
  make({ name: 'mulaigiveaway', category: CATEGORIES.GROUP, description: 'Mulai giveaway.', usage: 'a mulaigiveaway', role: 'admin' }),
  make({ name: 'startgiveaway', category: CATEGORIES.GROUP, description: 'Start giveaway.', usage: 'a startgiveaway', role: 'admin' }),
  make({ name: 'ikut', category: CATEGORIES.GROUP, description: 'Ikut giveaway.', usage: 'a ikut' }),
  make({ name: 'ikutgiveaway', category: CATEGORIES.GROUP, description: 'Ikut giveaway.', usage: 'a ikutgiveaway' }),
  make({ name: 'cekgiveaway', category: CATEGORIES.GROUP, description: 'Cek giveaway.', usage: 'a cekgiveaway' }),
  make({ name: 'rolling', category: CATEGORIES.GROUP, description: 'Rolling giveaway.', usage: 'a rolling', role: 'admin' }),
  make({ name: 'rollgiveaway', category: CATEGORIES.GROUP, description: 'Roll giveaway.', usage: 'a rollgiveaway', role: 'admin' }),
  make({ name: 'rollinggiveaway', category: CATEGORIES.GROUP, description: 'Rolling giveaway.', usage: 'a rollinggiveaway', role: 'admin' }),
  make({ name: 'deletegiveaway', category: CATEGORIES.GROUP, description: 'Hapus giveaway.', usage: 'a deletegiveaway', role: 'admin' }),
  make({ name: 'hapusgiveaway', category: CATEGORIES.GROUP, description: 'Hapus giveaway.', usage: 'a hapusgiveaway', role: 'admin' }),
  make({ name: 'pin', category: CATEGORIES.GROUP, description: 'Pin pesan.', usage: 'a pin', role: 'admin' }),
  make({ name: 'unpin', category: CATEGORIES.GROUP, description: 'Unpin pesan.', usage: 'a unpin', role: 'admin' }),
  make({ name: 'poll', category: CATEGORIES.GROUP, description: 'Buat polling.', usage: 'a poll pertanyaan|opsi1|opsi2', role: 'admin' }),
  make({ name: 'promote', category: CATEGORIES.GROUP, description: 'Naikkan jadi admin.', usage: 'a promote 628xx', role: 'admin', needsArgs: true }),
  make({ name: 'report', category: CATEGORIES.GROUP, description: 'Laporkan masalah.', usage: 'a report <teks>', needsArgs: true }),
  make({ name: 'reports', category: CATEGORIES.GROUP, description: 'Daftar report.', usage: 'a reports', role: 'admin' }),
  make({ name: 'restrict', category: CATEGORIES.GROUP, description: 'Restrict grup.', usage: 'a restrict on/off', role: 'admin' }),
  make({ name: 'mute', category: CATEGORIES.GROUP, description: 'Mute grup.', usage: 'a mute on/off', role: 'admin' }),
  make({ name: 'rules', category: CATEGORIES.GROUP, description: 'Lihat rules.', usage: 'a rules' }),
  make({ name: 'setrules', category: CATEGORIES.GROUP, description: 'Set rules.', usage: 'a setrules <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'privaterules', category: CATEGORIES.GROUP, description: 'Kirim rules private.', usage: 'a privaterules', role: 'admin' }),
  make({ name: 'resetrules', category: CATEGORIES.GROUP, description: 'Reset rules.', usage: 'a resetrules', role: 'admin' }),
  make({ name: 'setrulesbutton', category: CATEGORIES.GROUP, description: 'Set tombol rules.', usage: 'a setrulesbutton', role: 'admin' }),
  make({ name: 'templaterules', category: CATEGORIES.GROUP, description: 'Template rules.', usage: 'a templaterules', role: 'admin' }),
  make({ name: 'setppgc', category: CATEGORIES.GROUP, description: 'Set foto grup.', usage: 'a setppgc', role: 'admin' }),
  make({ name: 'setnamegc', category: CATEGORIES.GROUP, description: 'Set nama grup.', usage: 'a setnamegc <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'setdesgc', category: CATEGORIES.GROUP, description: 'Set deskripsi grup.', usage: 'a setdesgc <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'resetlinkgc', category: CATEGORIES.GROUP, description: 'Reset link grup.', usage: 'a resetlinkgc', role: 'admin' }),
  make({ name: 'slr', category: CATEGORIES.GROUP, description: 'Kirim alasan slow response.', usage: 'a slr <Alasan Slr>', needsArgs: true }),
  make({ name: 'spamtag', category: CATEGORIES.GROUP, description: 'Spam tag member.', usage: 'a spamtag <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'status', category: CATEGORIES.GROUP, description: 'Status grup.', usage: 'a status' }),
  make({ name: 'totalpesan', category: CATEGORIES.GROUP, description: 'Statistik pesan.', usage: 'a totalpesan' }),
  make({ name: 'upswgc', category: CATEGORIES.GROUP, description: 'Upload SW grup.', usage: 'a upswgc <teks>', role: 'admin' }),
  make({ name: 'swgc', category: CATEGORIES.GROUP, description: 'Lihat SW grup.', usage: 'a swgc' }),
  make({ name: 'swgrup', category: CATEGORIES.GROUP, description: 'Lihat SW grup.', usage: 'a swgrup' }),
  make({ name: 'votekick', category: CATEGORIES.GROUP, description: 'Voting kick.', usage: 'a votekick @tag', role: 'admin' }),
  make({ name: 'welcome', category: CATEGORIES.GROUP, description: 'Toggle welcome.', usage: 'a welcome <on/off>', role: 'admin', needsArgs: true }),
  make({ name: 'setwelcome', category: CATEGORIES.GROUP, description: 'Set template welcome.', usage: 'a setwelcome <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'changewelcome', category: CATEGORIES.GROUP, description: 'Ubah template welcome.', usage: 'a changewelcome <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'delsetwelcome', category: CATEGORIES.GROUP, description: 'Hapus template welcome.', usage: 'a delsetwelcome', role: 'admin' }),

  // MAIN
  make({ name: 'autoreply', category: CATEGORIES.MAIN, description: 'Toggle autoreply.', usage: 'a autoreply on/off', role: 'admin' }),
  make({ name: 'setautoreply', category: CATEGORIES.MAIN, description: 'Set autoreply.', usage: 'a setautoreply kata|balasan', role: 'admin' }),
  make({ name: 'delautoreply', category: CATEGORIES.MAIN, description: 'Hapus autoreply.', usage: 'a delautoreply kata', role: 'admin' }),
  make({ name: 'listautoreply', category: CATEGORIES.MAIN, description: 'List autoreply.', usage: 'a listautoreply' }),
  make({ name: 'claim', category: CATEGORIES.MAIN, description: 'Claim limit harian.', usage: 'a claim' }),
  make({ name: 'infobot', category: CATEGORIES.MAIN, description: 'Info bot.', usage: 'a infobot' }),
  make({ name: 'menu', category: CATEGORIES.MAIN, description: 'Menu utama.', usage: 'a menu' }),
  make({ name: 'allmenu', category: CATEGORIES.MAIN, description: 'Menu lengkap.', usage: 'a allmenu' }),
  make({ name: 'pinger', category: CATEGORIES.MAIN, description: 'Cek ping bot.', usage: 'a pinger' }),
  make({ name: 'speedtest', category: CATEGORIES.MAIN, description: 'Tes kecepatan (stub).', usage: 'a speedtest' }),
  make({ name: 'claimowner', category: CATEGORIES.MAIN, description: 'Klaim owner bot.', usage: 'a claimowner <password>', needsArgs: true }),

  // OWNER
  make({ name: 'addsewa', category: CATEGORIES.OWNER, description: 'Tambah sewa grup.', usage: 'a addsewa <idgrup> <hari>', role: 'owner', needsArgs: true }),
  make({ name: 'autobio', category: CATEGORIES.OWNER, description: 'Auto update bio.', usage: 'a autobio on/off', role: 'owner' }),
  make({ name: 'autopromosi', category: CATEGORIES.OWNER, description: 'Toggle autopromosi.', usage: 'a autopromosi <on/off>', role: 'owner', needsArgs: true }),
  make({ name: 'setpromosi', category: CATEGORIES.OWNER, description: 'Set teks promosi.', usage: 'a setpromosi <teks>', role: 'owner', needsArgs: true }),
  make({ name: 'backup', category: CATEGORIES.OWNER, description: 'Backup data.', usage: 'a backup', role: 'owner' }),
  make({ name: 'importstore', category: CATEGORIES.OWNER, description: 'Import store.', usage: 'a importstore', role: 'owner' }),
  make({ name: 'restore', category: CATEGORIES.OWNER, description: 'Restore data.', usage: 'a restore', role: 'owner' }),
  make({ name: 'broadcast', category: CATEGORIES.OWNER, description: 'Broadcast pesan.', usage: 'a broadcast <teks>', role: 'owner', needsArgs: true }),
  make({ name: 'broadcastpromo', category: CATEGORIES.OWNER, description: 'Broadcast promo.', usage: 'a broadcastpromo <teks>', role: 'owner', needsArgs: true }),
  make({ name: 'buatgrup', category: CATEGORIES.OWNER, description: 'Buat grup.', usage: 'a buatgrup <nama>', role: 'owner', needsArgs: true }),
  make({ name: 'cekexpired', category: CATEGORIES.OWNER, description: 'Cek masa sewa.', usage: 'a cekexpired', role: 'owner' }),
  make({ name: 'cleanup', category: CATEGORIES.OWNER, description: 'Bersih file sampah.', usage: 'a cleanup', role: 'owner' }),
  make({ name: 'cleantemp', category: CATEGORIES.OWNER, description: 'Bersih temp.', usage: 'a cleantemp', role: 'owner' }),
  make({ name: 'cleanuploads', category: CATEGORIES.OWNER, description: 'Bersih uploads.', usage: 'a cleanuploads', role: 'owner' }),
  make({ name: 'clearsession', category: CATEGORIES.OWNER, description: 'Bersih session.', usage: 'a clearsession', role: 'owner' }),
  make({ name: 'delsewa', category: CATEGORIES.OWNER, description: 'Hapus sewa.', usage: 'a delsewa <idgrup>', role: 'owner', needsArgs: true }),
  make({ name: 'eval', category: CATEGORIES.OWNER, description: 'Evaluasi kode (owner).', usage: 'a eval <kode>', role: 'owner', needsArgs: true }),
  make({ name: 'evalcode', category: CATEGORIES.OWNER, description: 'Evaluasi kode (owner).', usage: 'a evalcode <kode>', role: 'owner', needsArgs: true }),
  make({ name: 'hidetagsw', category: CATEGORIES.OWNER, description: 'Hidetag story.', usage: 'a hidetagsw <teks>', role: 'owner' }),
  make({ name: 'kirim', category: CATEGORIES.OWNER, description: 'Kirim pesan ke nomor.', usage: 'a kirim <nomor>|<teks>', role: 'owner', needsArgs: true }),
  make({ name: 'listsewa', category: CATEGORIES.OWNER, description: 'List sewa grup.', usage: 'a listsewa', role: 'owner' }),
  make({ name: 'owner', aliases: ['creator'], category: CATEGORIES.OWNER, description: 'Info owner.', usage: 'a owner' }),
  make({ name: 'playch', category: CATEGORIES.OWNER, description: 'Play channel (stub).', usage: 'a playch <judul>', role: 'owner' }),
  make({ name: 'premium', category: CATEGORIES.OWNER, description: 'Kelola premium user.', usage: 'a premium <add/del> <nomor>', role: 'owner', needsArgs: true }),
  make({ name: 'renewsewa', category: CATEGORIES.OWNER, description: 'Perpanjang sewa.', usage: 'a renewsewa <idgrup> <hari>', role: 'owner', needsArgs: true }),
  make({ name: 'restartbio', category: CATEGORIES.OWNER, description: 'Restart autobio.', usage: 'a restartbio', role: 'owner' }),
  make({ name: 'restartbot', category: CATEGORIES.OWNER, description: 'Restart bot.', usage: 'a restartbot', role: 'owner' }),
  make({ name: 'self', aliases: ['public'], category: CATEGORIES.OWNER, description: 'Mode self/public.', usage: 'a self / a public', role: 'owner' }),
  make({ name: 'setbotbio', category: CATEGORIES.OWNER, description: 'Set bio bot.', usage: 'a setbotbio <teks>', role: 'owner', needsArgs: true }),
  make({ name: 'setnamebot', category: CATEGORIES.OWNER, description: 'Set nama bot.', usage: 'a setnamebot <teks>', role: 'owner', needsArgs: true }),
  make({ name: 'setppbot', category: CATEGORIES.OWNER, description: 'Set foto bot.', usage: 'a setppbot', role: 'owner' }),
  make({ name: 'settings', category: CATEGORIES.OWNER, description: 'Lihat setting bot.', usage: 'a settings', role: 'owner' }),
  make({ name: 'upch', aliases: ['ch'], category: CATEGORIES.OWNER, description: 'Update channel.', usage: 'a upch <teks>', role: 'owner' }),
  make({ name: 'upswtag', category: CATEGORIES.OWNER, description: 'Upload story tag.', usage: 'a upswtag <teks>', role: 'owner' }),
  make({ name: 'version', category: CATEGORIES.OWNER, description: 'Versi bot.', usage: 'a version' }),

  // STORE
  make({ name: 'addlist', category: CATEGORIES.STORE, description: 'Tambah produk list.', usage: 'a addlist <nama>@<deskripsi>@<harga>', role: 'admin', needsArgs: true }),
  make({ name: 'dellist', category: CATEGORIES.STORE, description: 'Hapus produk by nama.', usage: 'a dellist <nama>', role: 'admin', needsArgs: true }),
  make({ name: 'dellistno', category: CATEGORIES.STORE, description: 'Hapus produk by nomor.', usage: 'a dellistno <no>', role: 'admin', needsArgs: true }),
  make({ name: 'updatelist', category: CATEGORIES.STORE, description: 'Update produk.', usage: 'a updatelist <nama>@<deskripsi>@<harga>', role: 'admin', needsArgs: true }),
  make({ name: 'clearlist', category: CATEGORIES.STORE, description: 'Hapus semua list produk.', usage: 'a clearlist', role: 'admin' }),
  make({ name: 'list', category: CATEGORIES.STORE, description: 'Lihat list produk.', usage: 'a list' }),
  make({ name: 'renamelist', category: CATEGORIES.STORE, description: 'Rename produk.', usage: 'a renamelist <lama>@<baru>', role: 'admin', needsArgs: true }),
  make({ name: 'setlist', category: CATEGORIES.STORE, description: 'Set template list.', usage: 'a setlist <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'resetsetlist', category: CATEGORIES.STORE, description: 'Reset template list.', usage: 'a resetsetlist', role: 'admin' }),
  make({ name: 'viewsetlist', category: CATEGORIES.STORE, description: 'Lihat template list.', usage: 'a viewsetlist' }),
  make({ name: 'viewlist', category: CATEGORIES.STORE, description: 'Lihat list produk.', usage: 'a viewlist' }),
  make({ name: 'previewsetlist', category: CATEGORIES.STORE, description: 'Preview template list.', usage: 'a previewsetlist' }),
  make({ name: 'previewlist', category: CATEGORIES.STORE, description: 'Preview list.', usage: 'a previewlist' }),
  make({ name: 'proses', aliases: ['.p'], category: CATEGORIES.STORE, description: 'Set order ke proses.', usage: 'a proses <id_order>|<catatan> / .p <id_order>|<catatan>', role: 'admin', needsArgs: true }),
  make({ name: 'done', aliases: ['.d'], category: CATEGORIES.STORE, description: 'Set order selesai.', usage: 'a done <id_order>|<catatan> / .d <id_order>|<catatan>', role: 'admin', needsArgs: true }),
  make({ name: 'batal', aliases: ['.b'], category: CATEGORIES.STORE, description: 'Set order batal.', usage: 'a batal <id_order>|<alasan> / .b <id_order>|<alasan>', role: 'admin', needsArgs: true }),
  make({ name: 'refund', aliases: ['.r'], category: CATEGORIES.STORE, description: 'Set order refund.', usage: 'a refund <id_order>|<alasan> / .r <id_order>|<alasan>', role: 'admin', needsArgs: true }),
  make({ name: 'pl', category: CATEGORIES.STORE, description: 'Daftar pesanan.', usage: 'a pl' }),
  make({ name: 'setproses', category: CATEGORIES.STORE, description: 'Set template proses.', usage: 'a setproses <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'setdone', category: CATEGORIES.STORE, description: 'Set template done.', usage: 'a setdone <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'changeproses', category: CATEGORIES.STORE, description: 'Ubah template proses.', usage: 'a changeproses <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'changerefund', category: CATEGORIES.STORE, description: 'Ubah template refund.', usage: 'a changerefund <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'changebatal', category: CATEGORIES.STORE, description: 'Ubah template batal.', usage: 'a changebatal <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'changedone', category: CATEGORIES.STORE, description: 'Ubah template done.', usage: 'a changedone <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'delsetproses', category: CATEGORIES.STORE, description: 'Hapus template proses.', usage: 'a delsetproses', role: 'admin' }),
  make({ name: 'delsetrefund', category: CATEGORIES.STORE, description: 'Hapus template refund.', usage: 'a delsetrefund', role: 'admin' }),
  make({ name: 'delsetdone', category: CATEGORIES.STORE, description: 'Hapus template done.', usage: 'a delsetdone', role: 'admin' }),
  make({ name: 'delsetbatal', category: CATEGORIES.STORE, description: 'Hapus template batal.', usage: 'a delsetbatal', role: 'admin' }),
  make({ name: 'feedback', category: CATEGORIES.STORE, description: 'Kirim feedback.', usage: 'a feedback <teks>', needsArgs: true }),
  make({ name: 'setsymbol', category: CATEGORIES.STORE, description: 'Set simbol list.', usage: 'a setsymbol <simbol>', role: 'admin', needsArgs: true }),
  make({ name: 'dollar', category: CATEGORIES.STORE, description: 'Konversi kurs dollar (stub).', usage: 'a dollar <nominal>', needsArgs: true }),
  make({ name: 'rupiah', category: CATEGORIES.STORE, description: 'Format rupiah (stub).', usage: 'a rupiah <nominal>', needsArgs: true }),
  make({ name: 'ringgit', category: CATEGORIES.STORE, description: 'Konversi ringgit (stub).', usage: 'a ringgit <nominal>', needsArgs: true }),
  make({ name: 'rupiah2ringgit', category: CATEGORIES.STORE, description: 'Konversi rupiah ke ringgit (stub).', usage: 'a rupiah2ringgit <nominal>', needsArgs: true }),
  make({ name: 'hutang', category: CATEGORIES.STORE, description: 'Tambah data hutang.', usage: 'a hutang <@tag/628xxxx>|<jumlah>|<catatan>', role: 'admin', needsArgs: true }),
  make({ name: 'listhutang', category: CATEGORIES.STORE, description: 'List hutang.', usage: 'a listhutang' }),
  make({ name: 'bayarhutang', category: CATEGORIES.STORE, description: 'Bayar hutang.', usage: 'a bayarhutang <id_hutang>|<jumlah>', role: 'admin', needsArgs: true }),
  make({ name: 'edithutang', category: CATEGORIES.STORE, description: 'Edit hutang.', usage: 'a edithutang <id_hutang>|<jumlah>|<catatan>', role: 'admin', needsArgs: true }),
  make({ name: 'hapushutang', category: CATEGORIES.STORE, description: 'Hapus hutang.', usage: 'a hapushutang <id>', role: 'admin', needsArgs: true }),
  make({ name: 'paymentdl', category: CATEGORIES.STORE, description: 'Lihat payment methods.', usage: 'a paymentdl' }),
  make({ name: 'setpayment', category: CATEGORIES.STORE, description: 'Tambah metode payment.', usage: 'a setpayment <metode>|<nama>|<nomor>|<note>', role: 'admin', needsArgs: true }),
  make({ name: 'updatepayment', category: CATEGORIES.STORE, description: 'Update metode payment.', usage: 'a updatepayment <metode>|<nama>|<nomor>|<note>', role: 'admin', needsArgs: true }),
  make({ name: 'delpayment', category: CATEGORIES.STORE, description: 'Hapus metode payment.', usage: 'a delpayment <metode>', role: 'admin', needsArgs: true }),
  make({ name: 'struk', category: CATEGORIES.STORE, description: 'Generate struk sederhana.', usage: 'a struk <nama>|<harga>|<qty>|<total>|<metode>', needsArgs: true }),
  make({ name: 'tambah', category: CATEGORIES.STORE, description: 'Kalkulator tambah.', usage: 'a tambah <angka1> <angka2>', needsArgs: true }),
  make({ name: 'kali', category: CATEGORIES.STORE, description: 'Kalkulator kali.', usage: 'a kali <angka1> <angka2>', needsArgs: true }),
  make({ name: 'kurang', category: CATEGORIES.STORE, description: 'Kalkulator kurang.', usage: 'a kurang <angka1> <angka2>', needsArgs: true }),
  make({ name: 'bagi', category: CATEGORIES.STORE, description: 'Kalkulator bagi.', usage: 'a bagi <angka1> <angka2>', needsArgs: true }),
  make({ name: 'persen', category: CATEGORIES.STORE, description: 'Hitung persen.', usage: 'a persen <angka> <persen>', needsArgs: true }),
  make({ name: 'pangkat', category: CATEGORIES.STORE, description: 'Hitung pangkat.', usage: 'a pangkat <angka> <pangkat>', needsArgs: true }),
  make({ name: 'testi', category: CATEGORIES.STORE, description: 'Lihat testimonial.', usage: 'a testi' }),
  make({ name: 'addtesti', category: CATEGORIES.STORE, description: 'Tambah testimonial.', usage: 'a addtesti <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'deltesti', category: CATEGORIES.STORE, description: 'Hapus testimonial.', usage: 'a deltesti <id>', role: 'admin', needsArgs: true }),
  make({ name: 'settesti', category: CATEGORIES.STORE, description: 'Set judul testimonial.', usage: 'a settesti <teks>', role: 'admin', needsArgs: true }),
  make({ name: 'exporttesti', category: CATEGORIES.STORE, description: 'Export testimonial.', usage: 'a exporttesti', role: 'admin' }),
  make({ name: 'importtesti', category: CATEGORIES.STORE, description: 'Import testimonial.', usage: 'a importtesti', role: 'admin' }),

  // TOOLS
  make({ name: 'bankstalk', category: CATEGORIES.TOOLS, description: 'Cek rekening bank (stub).', usage: 'a bankstalk <nomor>', needsArgs: true }),
  make({ name: 'ewalletstalk', category: CATEGORIES.TOOLS, description: 'Cek ewallet (stub).', usage: 'a ewalletstalk <nomor>', needsArgs: true }),
  make({ name: 'brat', category: CATEGORIES.TOOLS, description: 'Generate brat image.', usage: 'a brat <teks>', needsArgs: true }),
  make({ name: 'bratvid', category: CATEGORIES.TOOLS, description: 'Generate brat video.', usage: 'a bratvid <teks>', needsArgs: true }),
  make({ name: 'cekidch', category: CATEGORIES.TOOLS, description: 'Cek ID channel.', usage: 'a cekidch' }),
  make({ name: 'checkpln', aliases: ['cekpln'], category: CATEGORIES.TOOLS, description: 'Cek PLN (stub).', usage: 'a checkpln <idpel>', needsArgs: true }),
  make({ name: 'dompul', aliases: ['sidompul'], category: CATEGORIES.TOOLS, description: 'Cek dompul (stub).', usage: 'a dompul <nomor>', needsArgs: true }),
  make({ name: 'ffsearch', category: CATEGORIES.TOOLS, description: 'Cari akun Free Fire.', usage: 'a ffsearch <nickname/uid> [region]', needsArgs: true }),
  make({ name: 'ffstalk', category: CATEGORIES.TOOLS, description: 'Stalk akun Free Fire.', usage: 'a ffstalk <id>', needsArgs: true }),
  make({ name: 'fstik', category: CATEGORIES.TOOLS, description: 'Cari sticker pack (stub).', usage: 'a fstik <keyword>', needsArgs: true }),
  make({ name: 'getlid', aliases: ['lid'], category: CATEGORIES.TOOLS, description: 'Get LID akun.', usage: 'a getlid <id>', needsArgs: true }),
  make({ name: 'githubstalk', category: CATEGORIES.TOOLS, description: 'Stalk GitHub user.', usage: 'a githubstalk <username>', needsArgs: true }),
  make({ name: 'hdvideo', aliases: ['videohd'], category: CATEGORIES.TOOLS, description: 'Upgrade video HD (stub).', usage: 'a hdvideo' }),
  make({ name: 'iqc', category: CATEGORIES.TOOLS, description: 'Quote iPhone quality card.', usage: 'a iqc <time>|<battery>|<message>', needsArgs: true }),
  make({ name: 'mlstalk', category: CATEGORIES.TOOLS, description: 'Stalk Mobile Legends.', usage: 'a mlstalk <id>|<server>', needsArgs: true }),
  make({ name: 'npmstalk', category: CATEGORIES.TOOLS, description: 'Cek package npm.', usage: 'a npmstalk <package>', needsArgs: true }),
  make({ name: 'numverif', category: CATEGORIES.TOOLS, description: 'Verifikasi nomor.', usage: 'a numverif <nomor>', needsArgs: true }),
  make({ name: 'removebg', category: CATEGORIES.TOOLS, description: 'Hapus background (stub).', usage: 'a removebg' }),
  make({ name: 'rvo', category: CATEGORIES.TOOLS, description: 'Reverse voice (stub).', usage: 'a rvo' }),
  make({ name: 'spamngl', category: CATEGORIES.TOOLS, description: 'Spam NGL (stub).', usage: 'a spamngl <username>', needsArgs: true }),
  make({ name: 'ssweb', category: CATEGORIES.TOOLS, description: 'Screenshot website.', usage: 'a ssweb <url>', needsArgs: true }),
  make({ name: 'stikerly', category: CATEGORIES.TOOLS, description: 'Downloader stikerly.', usage: 'a stikerly <url>', needsArgs: true }),
  make({ name: 'telestick', category: CATEGORIES.TOOLS, description: 'Download telegram sticker.', usage: 'a telestick <url>', needsArgs: true }),
  make({ name: 'tourl', category: CATEGORIES.TOOLS, description: 'Upload media ke URL.', usage: 'a tourl' }),
  make({ name: 'upscale', category: CATEGORIES.TOOLS, description: 'Perbesar gambar.', usage: 'a upscale' }),
  make({ name: 'vcc', aliases: ['vccgen', 'vccvalidate', 'vcccek'], category: CATEGORIES.TOOLS, description: 'Generator/validator VCC.', usage: 'a vcc' }),
  make({ name: 'winkvideo', category: CATEGORIES.TOOLS, description: 'Edit video wink (stub).', usage: 'a winkvideo' }),
];

const commandMap = new Map();
for (const cmd of commands) {
  commandMap.set(cmd.name, cmd);
  for (const alias of cmd.aliases) commandMap.set(alias, cmd);
}

module.exports = {
  CATEGORIES,
  commands,
  commandMap,
};
